development: &postgres
  adapter: postgresql
  timeout: 5000
  encoding: utf8
  reconnect: false
  database: ciosa
  pool: 25
  username: postgres
  password: postgres
  host: 10.0.2.2
  port: 5432

production:
  <<: *postgres

staging:
  <<: *postgres
